@echo off

del *.pdb
del *.ilk
del *.exp
del *.lib
del *.ncb
del xmlOF\testCondor\OF\*.pdb
del xmlOF\testCondor\OF\*.ilk

del sifOF\debug\*.obj
del sifOF\debug\*.pdb
del sifOF\debug\*.idb
del sifOF\debug\buildLog.htm
rmdir sifOF\debug
del amplOF\debug\*.obj
del amplOF\debug\*.pdb
del amplOF\debug\*.idb
del amplOF\debug\buildLog.htm
rmdir amplOF\debug
del simpleOF\debug\*.obj
del simpleOF\debug\*.pdb
del simpleOF\debug\*.idb
del simpleOF\debug\buildLog.htm
rmdir simpleOF\debug
del xmlOF\dbtool\debug\*.obj
del xmlOF\dbtool\debug\*.pdb
del xmlOF\dbtool\debug\*.idb
del xmlOF\dbtool\debug\buildLog.htm
rmdir xmlOF\dbtool\debug
del xmlOF\debug\*.obj
del xmlOF\debug\*.pdb
del xmlOF\debug\*.idb
del xmlOF\debug\buildLog.htm
rmdir xmlOF\debug
del xmlOF\testCondor\OF\debug\*.obj
del xmlOF\testCondor\OF\debug\*.pdb
del xmlOF\testCondor\OF\debug\*.idb
del xmlOF\testCondor\OF\debug\buildLog.htm
rmdir xmlOF\testCondor\OF\debug
del matConvert\debug\*.obj
del matConvert\debug\*.pdb
del matConvert\debug\*.idb
del matConvert\debug\buildLog.htm
rmdir matConvert\debug
del sifOF\Release\*.obj
del sifOF\Release\*.pdb
del sifOF\Release\*.idb
del sifOF\Release\buildLog.htm
rmdir sifOF\Release
del amplOF\Release\*.obj
del amplOF\Release\*.pdb
del amplOF\Release\*.idb
del amplOF\Release\buildLog.htm
rmdir amplOF\Release
del simpleOF\Release\*.obj
del simpleOF\Release\*.pdb
del simpleOF\Release\*.idb
del simpleOF\Release\buildLog.htm
rmdir simpleOF\Release
del xmlOF\dbtool\Release\*.obj
del xmlOF\dbtool\Release\*.pdb
del xmlOF\dbtool\Release\*.idb
del xmlOF\dbtool\Release\buildLog.htm
rmdir xmlOF\dbtool\Release
del xmlOF\Release\*.obj
del xmlOF\Release\*.pdb
del xmlOF\Release\*.idb
del xmlOF\Release\buildLog.htm
rmdir xmlOF\Release
del xmlOF\testCondor\OF\Release\*.obj
del xmlOF\testCondor\OF\Release\*.pdb
del xmlOF\testCondor\OF\Release\*.idb
del xmlOF\testCondor\OF\Release\buildLog.htm
rmdir xmlOF\testCondor\OF\Release
del matConvert\Release\*.obj
del matConvert\Release\*.pdb
del matConvert\Release\*.idb
del matConvert\Release\buildLog.htm
rmdir matConvert\Release

echo press ctrl-c now if you want to keep the executables
pause
del *.exe
del xmlOF\testCondor\OF\*.exe
del xmlOF\testCondorwin32\*.exe
